name: Creative Warehouse
favicon: null
layout_spectrum: 0.6952650621533394
typography_spectrum: 0.3520305319689214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6601339217741042
  lightness: 0.5756613973062485
  saturation: 0.09272385109215975
  rhythmicContrast: 0.29424041230231524
purpose: []
